-- ============================================================
-- 064_identity_br_ddd_reference.sql — espelho de auditoria de VALID_DDD
--
-- GERADO por scripts/generate-ddd-constants.mjs a partir de
-- docs/reference/anatel-ddd.json (versão 1). NÃO editar manualmente.
-- Para atualizar: mudar o arquivo-fonte (Anexo A.1.4 incrementa "version")
-- e rodar o gerador (HOTFIX-001 A.6). O gerador também regrava 065 e
-- phone-identity.ts na mesma execução.
--
-- PAPEL: espelho para leitura humana/operacional (dashboards, auditoria)
-- e registro versionado usado pelo gerador. NUNCA é consultada por
-- canonical_br()/phone_identity() em runtime — a função IMMUTABLE usa o
-- array literal embutido no corpo de 065 (IDENT §8.2, HOTFIX-001 B.1).
-- ============================================================

CREATE TABLE IF NOT EXISTS identity_br_valid_ddd (
  ddd        CHAR(2) PRIMARY KEY,
  uf         CHAR(2) NOT NULL,
  source_ref TEXT NOT NULL,
  version    INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_identity_br_valid_ddd_version
  ON identity_br_valid_ddd (version);

INSERT INTO identity_br_valid_ddd (ddd, uf, source_ref, version) VALUES
  ('11', 'SP', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('12', 'SP', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('13', 'SP', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('14', 'SP', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('15', 'SP', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('16', 'SP', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('17', 'SP', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('18', 'SP', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('19', 'SP', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('21', 'RJ', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('22', 'RJ', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('24', 'RJ', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('27', 'ES', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('28', 'ES', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('31', 'MG', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('32', 'MG', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('33', 'MG', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('34', 'MG', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('35', 'MG', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('37', 'MG', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('38', 'MG', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('41', 'PR', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('42', 'PR', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('43', 'PR', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('44', 'PR', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('45', 'PR', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('46', 'PR', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('47', 'SC', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('48', 'SC', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('49', 'SC', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('51', 'RS', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('53', 'RS', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('54', 'RS', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('55', 'RS', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('61', 'DF', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('62', 'GO', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('63', 'TO', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('64', 'GO', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('65', 'MT', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('66', 'MT', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('67', 'MS', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('68', 'AC', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('69', 'RO', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('71', 'BA', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('73', 'BA', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('74', 'BA', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('75', 'BA', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('77', 'BA', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('79', 'SE', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('81', 'PE', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('82', 'AL', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('83', 'PB', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('84', 'RN', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('85', 'CE', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('86', 'PI', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('87', 'PE', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('88', 'CE', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('89', 'PI', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('91', 'PA', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('92', 'AM', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('93', 'PA', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('94', 'PA', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('95', 'RR', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('96', 'AP', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('97', 'AM', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('98', 'MA', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1),
  ('99', 'MA', 'Plano Geral de Códigos Nacionais (PGCN), aprovado pelo Despacho Decisório nº 12/2022/PRRE/SPR, publicado em 29/11/2022; consolidação por UF/município disponível em https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais e em https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais. Referência normativa: Resolução Anatel nº 749, de 15/03/2022 (Regulamento de Numeração), e Acórdão nº 202, de 14/08/2025 (faseamento das Áreas Locais do STFC). O Brasil está organizado em 67 áreas de numeração.', 1)
ON CONFLICT (ddd) DO NOTHING;
